### ISSUE TITLE
Delay after some minutes of use

### ISSUE THREAD

**Issue by Mitisuaki** [exeldro/obs-audio-monitor#53]
When I start my OBS everything is running fine, but after some minutes of use I start to percept some delay from every audio channel that I use Audio monitor.

What I can do to solve it is to change the output device to another one and then come back to the one that I use. But it is really annoying to do it 1 or 2 times per hours of live since I stream for about 7 or 8 hrs, if not more a day.
If I just restart my OBS it solves the problem too, but I can't do it while in live; I don't know why it happens, but since I use the audio monitor to stream using different audios for VOD and Live I need to use the audio monitor to listen everything.
Does anyone know anything that could be related to it and help me to solve it completely?

**Comment by Parcanss** [comment]
Having the same problem, the longer OBS is open and running the bigger the delay gets.

**Comment by iesvme** [comment]
I also have the same problem, especially if the video or network is stuck.

**Comment by iesvme** [comment]
> When I start my OBS everything is running fine, but after some minutes of use I start to percept some delay from every audio channel that I use Audio monitor.
> 
> What I can do to solve it is to change the output device to another one and then come back to the one that I use. But it is really annoying to do it 1 or 2 times per hours of live since I stream for about 7 or 8 hrs, if not more a day. If I just restart my OBS it solves the problem too, but I can't do it while in live; I don't know why it happens, but since I use the audio monitor to stream using different audios for VOD and Live I need to use the audio monitor to listen everything. Does anyone know anything that could be related to it and help me to solve it completely?

Excuse me. What OBS version do you use?

**Comment by KenFraserYT** [comment]
Experiencing this same issue in OBS V28.1.1 but was experiencing the issue before V28

**Comment by steven-archer** [comment]
OBS 29.1.0-rc1 + Audio Monitor 0.8.2

Can confirm what others are experiencing: A gradual increase in delay between OBS output and Audio Monitor output.

Steps to reproduce: Monitoring output over time, after about 15 to 20 minutes it starts to become more noticable, especially when comparing to the "Monitor and Output" setting enabled in Advanced Audio Properties, or even just by looking at the built-in mixer. The delay resets when restarting OBS, but will gradually increase again over time.

**Comment by y4m4p** [comment]
obs29.1.3, Audio Monitor 0.8.3

Confirmed, this still is an ongoing issue. Thought my capture device was lagging and tried changing the frequency and delay values, but to no avail.
Can be periodically fixed or resolved by re-initializing (or clicking the eye icon) the source object, but its pretty tedious and it becomes apparently noticeable after 1 minute and onwards, so it's not a feasible solution.

Sadly moving away because of this issue since it's not tolerable on my end. Just gonna use the OG audio monitoring for the while being.

**Comment by Lordmau5** [comment]
Still an issue on OBS 31.1.1 with the newest Audio Monitor version.

I unfortunately have to use a plugin like this to output my capture card directly onto my headphones as Elgato's WaveLink adds extra, very noticeable delay (around 100ms, if not more)

As others mentioned, initially it's fine and in sync, but over time it gets delayed. Toggling the source / filter fixes it but it will return after a while.
